---
title: "HEG vs QoL models"
author: "Alison E. Turnbull"
date: '2022-07-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading data, echo=FALSE}
# This next line of code will need to change to reflect where you've saved your project locally.  
# In this case, the data - named "20220526_OSEAR_cleaning.RData" has been saved within the project on a network drive.

# load("H:/K01 research/Aim 3 - Cohort Study/OSEAR data/OSEAR_QoL_paper_share/20220526_OSEAR_cleaning.RData")
```

```{r packages, include=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(plyr)
library(dplyr)
library(janitor)
library(table1)
library(finalfit)
```


```{r, number of independent i/adls, echo=FALSE, include=FALSE}
ind_ADL<- df %>%
        select(starts_with("mo6_")) %>%
          #filter(!is.na(mo6_bathing)) %>%      # There are 26 people missing data on ADL independence at 6 months
          select(-c(mo6_continence, mo6_laundry_fct)) %>%
            dplyr::mutate(across(everything(), ~ifelse(.x =="Independent", 1, 0))) %>%
                rowwise() %>%
                    dplyr::mutate(n_ind=sum(c_across(cols=everything())))

df<-cbind(df, ind_ADL$n_ind)
new_var<-length(df)
names(df)[new_var]<-"n_ind"
```


```{r Create HEG variable, echo=FALSE, include=FALSE}

#Calculating the health expectation gap (HEG)
df <- df %>%
        mutate(heg=eqol_vas - exp_vas)
```

<!-- Guidance : https://m-clark.github.io/generalized-additive-models/application.html#single-predictor -->

```{r modeling WHOQOL-Physical (e-Table 2), echo=FALSE, include=FALSE}
library(gam)
library(mgcv)

# Remove missing data
temp_1<-df %>%
          drop_na(heg, whoqol_d1_100) %>%
            select(whoqol_d1_100, heg, age, sex, n_ind, mspss_6mo_total, cd_score, eqol_vas)

temp_2<-df %>%
          drop_na(heg, whoqol_d2_100) %>%
            select(whoqol_d2_100, heg, age, sex, n_ind, mspss_6mo_total, cd_score, eqol_vas)

temp_3<-df %>%
          drop_na(heg, whoqol_d3_100) %>%
            select(whoqol_d3_100, heg, age, sex, n_ind, mspss_6mo_total, cd_score, eqol_vas)

temp_4<-df %>%
          drop_na(heg, whoqol_d4_100) %>%
            select(whoqol_d4_100, heg, age, sex, n_ind, mspss_6mo_total, cd_score, eqol_vas)

# Fitting models for each domain score with cubic regression splines for the HEG variable in each. 
# Will compare to models without the spline for each and then decide whether they improve fit. 

#Physical domain
physical_model_s<-gam(whoqol_d1_100 ~ s(heg, bs="cr") + age + sex + n_ind  + mspss_6mo_total+ cd_score + eqol_vas, family = gaussian, data=temp_1)

physical_model_l<-gam(whoqol_d1_100 ~ heg + age + sex + n_ind  + mspss_6mo_total+ cd_score + eqol_vas, family = gaussian, data=temp_1)

anova(physical_model_s, physical_model_l, test = "Chisq")  # Pr(>Chi) = 0.002

#Psych domain
psych_model_s<-gam(whoqol_d2_100 ~ s(heg, bs="cr") + age + sex + n_ind  + mspss_6mo_total+ cd_score + eqol_vas, family = gaussian, data=temp_2)

psych_model_l<-gam(whoqol_d2_100 ~ heg + age + sex + n_ind  + mspss_6mo_total+ cd_score + eqol_vas, family = gaussian, data=temp_2)

anova(psych_model_s, psych_model_l, test = "Chisq")  # Pr(>Chi) = 0.05

#Social
social_model_s<-gam(whoqol_d3_100 ~ s(heg, bs="cr") + age + sex + n_ind  + mspss_6mo_total + cd_score + eqol_vas, family = gaussian, data=temp_3)

social_model_l<-gam(whoqol_d3_100 ~ heg + age + sex + n_ind  + mspss_6mo_total + cd_score + eqol_vas, family = gaussian, data=temp_3)

## edf = 1 in the non-linear model so no need to test

#Environmental
envir_model_s<-gam(whoqol_d4_100 ~ s(heg, bs="cr") + age + sex + n_ind  + mspss_6mo_total + cd_score + eqol_vas, family = gaussian, data=temp_4)

envir_model_l<-gam(whoqol_d4_100 ~ heg + age + sex + n_ind  + mspss_6mo_total + cd_score + eqol_vas, family = gaussian, data=temp_4)

anova(envir_model_s, envir_model_l, test = "Chisq")  # Pr(>Chi) = 0.11

export_model<-rbind(summary.gam(physical_model_s)$p.table, summary.gam(psych_model_l)$p.table, summary.gam(social_model_l)$p.table, summary.gam(envir_model_l)$p.table)

write.csv(export_model, here::here("tables","20220726_Model_summaries.csv"))
```

```{r Visualizing effects for Physical Health domain in a prototypical participant (Fig 3), echo=FALSE, include=FALSE}

# Creating a new dataset with mean/mode values for covariates

testdata = data.frame(
                heg = seq(-35, 15, length=51), 
                age = mean(physical_model_s$model$age),  #53
                sex = "male",   
                n_ind = 12,
                mspss_6mo_total = median(physical_model_s$model$mspss_6mo_total), #71
                eqol_vas = 65,                #Note, setting this to 50 allows HEG to be a large range of values
                cd_score = median(physical_model_s$model$cd_score))               #35               
                  

physical_predictions = predict(
                          physical_model_s,
                          newdata = testdata,
                          type = 'response',
                          se = TRUE)

physical_preds = data.frame(testdata, physical_predictions) %>%
  mutate(lower = fit - 1.96 * se.fit,
         upper = fit + 1.96 * se.fit, 
         domain = "Physical health")


fig3<-ggplot(aes(x = heg, y = fit), data = physical_preds) +
                        geom_ribbon(aes(ymin = lower, ymax = upper), fill = 'gray92') +
                        geom_line(color = 'blue') + 
                          labs(title="Predicted quality of life for a standardized patient" , 
                                  x="Health Expectation Gap at 6 months", 
                                  y="Predicted WHOQoL-BREF physical health domain score") + 
                              scale_x_continuous(limits=c(-35, 15), breaks=c(-30, -20, -10, 0, 10)) +
                              scale_y_continuous(limits=c(39, 101), breaks=c(50, 60, 70, 80, 90, 100)) +
                              geom_vline(xintercept = 0, linetype="dashed") + 
                                theme_bw() + 
                                theme(aspect.ratio = 1)


## Example patient
signif(physical_preds[which(physical_preds$heg==-35), c("fit", "lower", "upper")], 3)
#     fit lower upper
#    55.5  45.8  65.1

signif(physical_preds[which(physical_preds$heg==0), c("fit", "lower", "upper")], 3)
#     fit lower upper
#    71.5  65.2  77.8


```


