---
title: "HEG vs QoL models"
author: "Alison E. Turnbull"
date: '2022-06-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading df tab1 and tab2 from March 28, echo=FALSE}
load("H:/K01 research/Aim 3 - Cohort Study/OSEAR data/OSEAR_QoL_paper/20220526_OSEAR_cleaning.RData")
```

```{r packages, include=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(plyr)
library(dplyr)
library(janitor)
library(table1)
library(finalfit)
```

```{r, number of independent i/adls, echo=FALSE, include=FALSE}
ind_ADL<- df %>%
        select(starts_with("mo6_")) %>%
          #filter(!is.na(mo6_bathing)) %>%      # There are 26 people missing data on ADL independence at 6 months
          select(-c(mo6_continence, mo6_laundry_fct)) %>%
            dplyr::mutate(across(everything(), ~ifelse(.x =="Independent", 1, 0))) %>%
                rowwise() %>%
                    dplyr::mutate(n_ind=sum(c_across(cols=everything())))

```




```{r Expectation gap vs QoL figure, echo=FALSE, include=FALSE}

#Calculating the health expectation gap (HEG)
df <- df %>%
        mutate(heg=eqol_vas - exp_vas)

## Adding number of IADLs performed independently at 6 months to the dataframe
df<-cbind(df, ind_ADL$n_ind)
names(df)[154]<-"n_iadl_independent"

# Creating a long version of dataframe
df_long <- df %>%
            select(id, heg, whoqol_d1_100, whoqol_d2_100, whoqol_d3_100, whoqol_d4_100) %>%
                pivot_longer(cols = starts_with("whoqol_"), 
                                    names_to="domain", 
                                    values_to="score")
# Re-labeling domain names
df_long$domain<-fct_recode(df_long$domain, 'Physical health' ="whoqol_d1_100", 'Psychological health' ="whoqol_d2_100", 'Social relationships' = "whoqol_d3_100", 'Environment health' ="whoqol_d4_100")
  

# Faceted scatterplot
HEG_vs_QoL<-df_long %>%
                    ggplot(aes(x=heg, y=score)) + 
                        geom_jitter(width = 1, height=1, alpha=.5) +
                          geom_smooth(span=.8) +
                           geom_vline(xintercept = 0, linetype="dashed") + 
                            labs(title="Health Expectation Gap vs Quality of Life (N = 139)", 
                            x="Health expectation gap at 6 months", 
                            y="WHOQoL-BREF domain score at 6 months") + 
                              scale_x_continuous(limits=c(-100, 50), breaks=c(-100, -75, -50, -25, 0, 25, 50)) +
                              scale_y_continuous(limits=c(-1, 101), breaks=c(0, 25, 50, 75, 100)) +
                                theme_bw() +
                                  theme(aspect.ratio = .8) +
                                    facet_wrap(~domain)
```

```{r SCatterplot matrix, echo=FALSE, include=FALSE}
library(GGally)

# Remove missing data
temp_1<-df %>%
          drop_na(heg, whoqol_d1_100) %>%
            select(whoqol_d1_100, heg, age, sex, n_iadl_independent, mspss_6mo_total, cd_score)

temp_2<-df %>%
          drop_na(heg, whoqol_d2_100) %>%
            select(whoqol_d2_100, heg, age, sex, n_iadl_independent, mspss_6mo_total, cd_score)

temp_3<-df %>%
          drop_na(heg, whoqol_d3_100) %>%
            select(whoqol_d3_100, heg, age, sex, n_iadl_independent, mspss_6mo_total, cd_score)

temp_4<-df %>%
          drop_na(heg, whoqol_d4_100) %>%
            select(whoqol_d4_100, heg, age, sex, n_iadl_independent, mspss_6mo_total, cd_score)


correlogram_physical<-ggpairs(temp_1, title="Correlogram with Physical Health")
correlogram_psych<-ggpairs(temp_2, title="Correlogram with Physical Health")
correlogram_social<-ggpairs(temp_3, title="Correlogram with Physical Health")
correlogram_environmental<-ggpairs(temp_4, title="Correlogram with Physical Health")

```




```{r Fitting splines for the HEG, echo=FALSE, include=FALSE}
library(splines)
library(npreg)

# Fit a smoothing spline for the relationship between HEG and WHOQOL domains
mod.ss_1<-with(temp_1, ss(heg, whoqol_d1_100))

# Smoothing Parameter  spar = 0.4073565   lambda = 5.227771e-05
# Equivalent Degrees of Freedom (Df) 4.661531
# Penalized Criterion (RSS) 52713.98
# Generalized Cross-Validation (GCV) 412.3577 

mod.ss_2<-with(temp_2, ss(heg, whoqol_d2_100))

# Smoothing Parameter  spar = 0.4185096   lambda = 6.293541e-05
# Equivalent Degrees of Freedom (Df) 4.486647
# Penalized Criterion (RSS) 37251.97
# Generalized Cross-Validation (GCV) 290.6367

mod.ss_3<-with(temp_3, ss(heg, whoqol_d3_100))
# Smoothing Parameter  spar = 1.5   lambda = 4095.997
# Equivalent Degrees of Freedom (Df) 2                      <- Note - Df = 2, hence, spline is not improving fit
# Penalized Criterion (RSS) 43247.52
# Generalized Cross-Validation (GCV) 327.5597 

mod.ss_4<-with(temp_4, ss(heg, whoqol_d4_100))
# Smoothing Parameter  spar = 1.5   lambda = 4095.997
# Equivalent Degrees of Freedom (Df) 2                      <- Note - Df = 2, hence, spline is not improving fit
# Penalized Criterion (RSS) 34752.85
# Generalized Cross-Validation (GCV) 261.2423 


heg_WHOQOL1_splineplot<-plot(mod.ss_1, xlab="HEG", ylab = "WHOQOL-Physical") + rug(temp_1$heg) 
heg_WHOQOL2_splineplot<-plot(mod.ss_2, xlab="HEG", ylab = "WHOQOL-Psychological") + rug(temp_2$heg) 
heg_WHOQOL3_splineplot<-plot(mod.ss_3, xlab="HEG", ylab = "WHOQOL-Social") + rug(temp_3$heg) 
heg_WHOQOL4_splineplot<-plot(mod.ss_4, xlab="HEG", ylab = "WHOQOL-Environmental") + rug(temp_4$heg) 

```

```{r modeling WHOQOL-Physical, echo=FALSE, include=FALSE}
library(gam)

physical_1<-gam(whoqol_d1_100 ~ s(heg, spar = 0.4073565) + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_1)
plot(physical_1, se=TRUE)

psych_1<-gam(whoqol_d2_100 ~ s(heg, spar = 0.4185096) + age + sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_2)
plot(psych_1, se=TRUE)

social_1<-gam(whoqol_d3_100 ~ heg + age + sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_3)
plot(social_1, se=TRUE)

envir_1<-gam(whoqol_d4_100 ~ heg + age + sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_4)
plot(envir_1, se=TRUE)

```

```{r examining residual plots, echo=FALSE, include=FALSE}
plot.Gam(physical_1, residuals=TRUE, se=TRUE)
plot.Gam(psych_1, residuals=TRUE, se=TRUE)
plot.Gam(social_1, residuals=TRUE, se=TRUE)
plot.Gam(envir_1, residuals=TRUE, se=TRUE)
```

```{r modeling using mcgv package, echo=FALSE, include=FALSE}

detach("package:gam", unload = TRUE) # Note that the gam and mgcv packages don't play well together so need to detach first.
library(mgcv)
# Guidance : https://m-clark.github.io/generalized-additive-models/application.html#single-predictor

#First just a linear model
physical_lm<-gam(whoqol_d1_100 ~ heg + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_1)
summary(physical_lm)

#Now looking for non-linear effects of each predictor
physical_nl<-gam(whoqol_d1_100 ~ s(heg) + s(age) +sex + s(mspss_6mo_total) + n_iadl_independent + s(cd_score), family = gaussian, data=temp_1)
summary(physical_nl)

physical_nl_2<-gam(whoqol_d1_100 ~ s(heg) + s(age) +sex + s(mspss_6mo_total) + n_iadl_independent + cd_score, family = gaussian, data=temp_1)
summary(physical_nl_2)

physical_nl_cr<-gam(whoqol_d1_100 ~ s(heg, bs="cr") + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_1)
summary(physical_nl_cr)

physical_nl_justheg<-gam(whoqol_d1_100 ~ s(heg) + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_1)
summary(physical_nl_justheg)

AIC(physical_nl)         #1094.69
AIC(physical_nl_2)       #1096.23
AIC(physical_nl_cr)      #1104.44
AIC(physical_nl_justheg) #1103.61

summary(physical_nl)$r.sq          #0.60
summary(physical_nl_2)$r.sq        #0.58
summary(physical_nl_cr)$r.sq       #0.55
summary(physical_nl_justheg)$r.sq  #0.55

## Ok, I think the simplest model is best and doesn't lose much in terms of fit.  
physical_gam<-gam(whoqol_d1_100 ~ s(heg) + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_1)
psych_gam<-gam(whoqol_d2_100 ~ s(heg) + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_2)
social_gam<-gam(whoqol_d3_100 ~ s(heg) + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_3)
envir_gam<-gam(whoqol_d4_100 ~ s(heg) + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_4)


## Run anovas for models with and without splines of heg to test if this is improving fit significantly
physical_gam_test<-gam(whoqol_d1_100 ~ heg + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_1)
psych_gam_test<-gam(whoqol_d2_100 ~ heg + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_2)
social_gam_test<-gam(whoqol_d3_100 ~ heg + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_3)
envir_gam_test<-gam(whoqol_d4_100 ~ heg + age +sex + mspss_6mo_total + n_iadl_independent + cd_score, family = gaussian, data=temp_4)

anova(physical_gam_test, physical_gam, test="F")  #P=0.0099
anova(psych_gam_test, psych_gam, test="F")        #P=0.08
anova(social_gam_test, social_gam, test="F")      #P<0.001
anova(envir_gam_test, envir_gam, test="F")        #P<0.08

### Look at residual plots
qqnorm(residuals(physical_gam))
qqnorm(residuals(psych_gam))
qqnorm(residuals(social_gam))
qqnorm(residuals(envir_gam))

### Predicted vs residuals
plot(predict(physical_gam), residuals(physical_gam), xlab="Predicted", ylab="Residuals")

```


```{r visualizing physical health model results, echo=FALSE, include=FALSE}
library(visreg)
visreg(physical_gam, "heg")
visreg(physical_gam, "heg",  jitter = TRUE, 
       xlab = "Health Expectation Gap", 
       ylab = "Predicted WHOQOL-BREF Physical Health Domain Score", 
       main = "Physical Health Domain score for a standardized patient",  
       ylim(0, 80)) +
          theme_bw()

plot1_ph<-visreg(physical_gam, "heg", ylab="Physical Health", ylim=c(0, 100), xlim=c(-50, 30), 
       jitter = TRUE, xlab = "Health Expectation Gap", 
       ylab = "Predicted WHOQOL-BREF Physical Health Domain Score", 
       main = "Predicted QoL for a 53 yo male with all I/ADLs and median values") +
          theme_bw()


plot2_ph<-visreg(physical_gam, "heg", type="contrast", xlim=c(-50, 30), 
       jitter = TRUE, xlab = "Health Expectation Gap", gg=TRUE,
       ylab = "Change in WHOQOL-BREF Physical Health Domain Score") + 
          theme_bw() + 
          geom_hline(yintercept=0, color="red", linetype="dashed") + 
          geom_vline(xintercept=-12, color="red") 

visreg2d(physical_gam, "heg", "n_iadl_independent", xlim=c(-40, 20), ylim=c(6, 12), plot.type="image", 
         xlab = "Health Expectation Gap", 
         ylab = "Number of I/ADLS performed independently at 6 months", 
         main = "Predicted WHOQOL-BREF physical domain score") 
```


```{r visualizing psych health model results, echo=FALSE, include=FALSE}

plot1_psych<-visreg(psych_gam, "heg",  jitter = TRUE, ylim=c(0, 100), xlim=c(-50, 30), 
       xlab = "Health Expectation Gap", 
       ylab = "Predicted WHOQOL-BREF Psychological Health Domain Score", 
       main = "Psychological Health Domain score for a standardized patient") +
          theme_bw()

plot2_psych<-visreg(psych_gam, "heg", type="contrast", xlim=c(-50, 30), 
       jitter = TRUE, xlab = "Health Expectation Gap", gg=TRUE,
       ylab = "Change in WHOQOL-BREF Psychological Health Domain Score") + 
          theme_bw() + 
          geom_hline(yintercept=0, color="red", linetype="dashed") + 
          geom_vline(xintercept=-12, color="red") 

visreg2d(psych_gam, "heg", "cd_score", xlim=c(-40, 20), plot.type="image", 
         xlab = "Health Expectation Gap", 
         ylab = "CD-risc score", 
         main = "Predicted WHOQOL-BREF psychological domain score") 
```


```{r visualizing social health model results, echo=FALSE, include=FALSE}
plot1_social<-visreg(social_gam, "heg",  jitter = TRUE, ylim=c(0, 100), xlim=c(-50, 30), 
       xlab = "Health Expectation Gap", 
       ylab = "Predicted WHOQOL-BREF Social Relationships Score", 
       main = "Social Relationships score for a standardized patient") +
          theme_bw()

plot2_social<-visreg(social_gam, "heg", type="contrast", xlim=c(-50, 30), 
       jitter = TRUE, xlab = "Health Expectation Gap", gg=TRUE,
       ylab = "Change in WHOQOL-BREF Social Relationships Score") + 
          theme_bw() + 
          geom_hline(yintercept=0, color="red", linetype="dashed") + 
          geom_vline(xintercept=-12, color="red") 

visreg2d(social_gam, "heg", "mspss_6mo_total", xlim=c(-40, 20), plot.type="image", 
         xlab = "Health Expectation Gap", 
         ylab = "MSPSS score", 
         main = "Predicted WHOQOL-BREF Social Relationships score") 
```


```{r visualizing Environment health model results, echo=FALSE, include=FALSE}
plot1_envir<-visreg(envir_gam, "heg",  jitter = TRUE, ylim=c(0, 100), xlim=c(-50, 30), 
       xlab = "Health Expectation Gap", 
       ylab = "Predicted WHOQOL-BREF Environment Score", 
       main = "Social Relationships score for a standardized patient") +
          theme_bw()

plot2_envir<-visreg(envir_gam, "heg", type="contrast", xlim=c(-50, 30), 
       jitter = TRUE, xlab = "Health Expectation Gap", gg=TRUE,
       ylab = "Change in WHOQOL-BREF Environmental Health Score") + 
          theme_bw() + 
          geom_hline(yintercept=0, color="red", linetype="dashed") + 
          geom_vline(xintercept=-12, color="red") 

visreg2d(envir_gam, "heg", "n_iadl_independent", xlim=c(-40, 20), ylim=c(6, 12),plot.type="image", 
         xlab = "Health Expectation Gap", 
         ylab = "Number of I/ADLS performed independently", 
         main = "Predicted WHOQOL-BREF Environmental Health score") 
```
